### ISSUE TITLE
Bringing dialog up when keyboard opens

### ISSUE THREAD

**Issue by Skquark** [nizwar/ndialog#1]
Love this dialog box addon, I've tried out 5 different ones to add the style I wanted, and this one's my favorite, thanks.  Anyways, in my usage, I have a stack of input fields that bring up the system keyboard, and it's cutting off the ui that's needed.  I wanted the box to align to the top when the keyboard comes up to make room, so I went ahead and added a simple mod to your code and got it working exactly how anyone would want it, I recommend adding this feature to your next update... In ndialog_base.dart on the Stack right under the WillPopScope, I changed it to this:

`child: Stack(alignment: MediaQuery.of(context).viewInsets.bottom == 0 ? Alignment.center : Alignment.topCenter, children: <Widget>[ `
That's it, all it took, works like a charm.. Thanks again, looking forward to any other future updates. Cheers.

**Comment by nizwar** [comment]
Thank you for your feedback, i think, i found a better way, will update soon 👏

**Comment by nizwar** [comment]
Updated

**Comment by Skquark** [comment]
Excellent, thanks.  Got the update, love what you did with the DialogStyle too.  Much appreciated.
