### ISSUE TITLE
How to close dialog in insider actions?

### ISSUE THREAD

**Issue by TortuC** [nizwar/ndialog#10]
![image](https://user-images.githubusercontent.com/65579678/144719602-d4e6d81c-29fd-4152-936e-0955b1eae2a1.png)
I want to close the dialog by clicking the ok button on this screen.
but I can't find any method for that in this dialog package.

**Comment by nizwar** [comment]
You can use Navigator.pop(context) to NAlertDialog, and use .dismiss() on ProgressDialog
Duplicate of #8
