### ISSUE TITLE
how to dismiss NDialog programmatically

### ISSUE THREAD

**Issue by wmhseir3** [nizwar/ndialog#11]
as seen in title. there is no dismiss method as with the NDialog. 
is there any way to do so now or in the next release?
thanks.

**Comment by ChandAbdullah** [comment]
in NAlertDialog, how to dismiss dialog programmatically?
Please provider us.

**Comment by nizwar** [comment]
You can use Navigator.pop(context) to NAlertDialog, and use .dismiss() on ProgressDialog.. i'll close this issues as
duplicate of #8
