### ISSUE TITLE
Error: 'DialogThemeData' isn't a type in Error

### ISSUE THREAD

**Issue by Yetispapa** [nizwar/ndialog#17]
Hi there,

after updating to v4.4.0, I got the error: Error: `'DialogThemeData' isn't a type in Error`. It seems, there is an import missing?

Can you help here :)

**Comment by nizwar** [comment]
DialogThemeData is coming from flutter 3.27.0
https://docs.flutter.dev/release/breaking-changes/component-theme-normalization#migration-guide

You might need to downgrade your ndialog version to 4.3.1 or upgrade your flutter version

**Comment by nizwar** [comment]
Meanwhile i'll close this issue, feel free to open it again if you still encounter similiar issues
