### ISSUE TITLE
Expected a value of type 'SkDeletable', but got one of type 'Null'

### ISSUE THREAD

**Issue by ajaysanity** [nizwar/ndialog#4]
I see this error on flutter Web. 

> ======== Exception caught by widgets library 
> The following TypeErrorImpl was thrown building TweenAnimationBuilder<double>(duration: 300ms, dirty, dependencies: [_EffectiveTickerMode], state: _TweenAnimationBuilderState<double>#7141f(ticker inactive)):
> Expected a value of type 'SkDeletable', but got one of type 'Null'
> 
> The relevant error-causing widget was: 
>   MaterialApp file:///D:/xxx/xx.xx/lib/main.dart:24:14
> When the exception was thrown, this was the stack: 
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 84:3    castError
> C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart 266:34   as
> C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/skia_object_cache.dart 146:55    new
> C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/image_filter.dart 26:3           __
> ...
> 

I used your example on progress dialog. 

Flutter Doctor:

> Flutter 2.0.2 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 8962f6dc68 (6 days ago) • 2021-03-11 13:22:20 -0800
> Engine • revision 5d8bf811b3
> Tools • Dart 2.12.1

**Comment by nizwar** [comment]
Hi, Thank you for open this issue, 
I'm working on this bug fixes,  i'll let you know when it published

**Comment by nizwar** [comment]
Hi, i've update the plugin to v4.0.1 , you can try it now

**Comment by ajaysanity** [comment]
Great! I appreciate it. Thank you
