### ISSUE TITLE
Feature Request: State management

### ISSUE THREAD

**Issue by ajaysanity** [nizwar/ndialog#6]
It would be great if the dialog will rebuild when there is a state management (Bloc, providers,rxdart etc.) or just a simple setState.

**Comment by nizwar** [comment]
Hi, thanks for your request, can you tell me more details about this feature and explain about your cases which maybe I will have better insight and will consider to make this feature before i launch the update.

can't wait to hear it from you...

**Comment by nizwar** [comment]
You can use State management inside the widget that you want to manipulate and show them as Dialog using DialogBackground or NAlertDialog...

Since there is no further information about this, i'll close this issue, feel free to open this issue if you want to discussed about it
