### ISSUE TITLE
Can't dismiss CustomProgressDialog

### ISSUE THREAD

**Issue by rooneyviet** [nizwar/ndialog#9]
ndialog: ^4.1.0

progressDialog.dismiss();

your code dismiss() method

```
void dismiss() {
    if (_show) {
      _show = false;
      Navigator.pop(context);
    }
  }
```

_show is always false, although progressdialog showing on screen.

**Comment by nizwar** [comment]
Thanks for your report, can you also provide your use case code on that?

**Comment by rooneyviet** [comment]
@nizwar 

yes! I moved to initState and it's fixed 
I didn't think about that. I wondered how it always false lol.

thanks 😀😘
